package io.swagger.api.client.account.model;

/**
 * Petstore Sample Application on Spring Cloud 
 * 
 * Auto-generated by api-client-codegen.
 */
public class User {


    private java.time.LocalDate birth;

    public java.time.LocalDate getBirth() {
        return this.birth;
    }
    
    public void setBirth(java.time.LocalDate birth) {
        this.birth = birth;
    }
    private Long createdAt;

    public Long getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Long createdAt) {
        this.createdAt = createdAt;
    }
    private String createdBy;

    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    private String email;

    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    private String gender;

    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    private String id;

    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    private String name;

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    private Integer role;

    public Integer getRole() {
        return this.role;
    }
    
    public void setRole(Integer role) {
        this.role = role;
    }
    private Long updatedAt;

    public Long getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Long updatedAt) {
        this.updatedAt = updatedAt;
    }
    private String updatedBy;

    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }
    private Long version;

    public Long getVersion() {
        return this.version;
    }
    
    public void setVersion(Long version) {
        this.version = version;
    }
}
