package io.swagger.api.client.account.model;

/**
 * Petstore Sample Application on Spring Cloud 
 * 
 * Auto-generated by api-client-codegen.
 */
public class UserBean {


    private java.time.LocalDate birth;

    public java.time.LocalDate getBirth() {
        return this.birth;
    }
    
    public void setBirth(java.time.LocalDate birth) {
        this.birth = birth;
    }
    private String email;

    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    private String gender;

    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    private String name;

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
}
