package io.swagger.api.client.account.model;

/**
 * Petstore Sample Application on Spring Cloud 
 * 
 * Auto-generated by api-client-codegen.
 */
public class Page<T> {


    private java.util.List<T> content;

    public java.util.List<T> getContent() {
        return this.content;
    }
    
    public void setContent(java.util.List<T> content) {
        this.content = content;
    }
    private Boolean first;

    public Boolean isFirst() {
        return this.first;
    }
    
    public void setFirst(Boolean first) {
        this.first = first;
    }
    private Boolean last;

    public Boolean isLast() {
        return this.last;
    }
    
    public void setLast(Boolean last) {
        this.last = last;
    }
    private Integer number;

    public Integer getNumber() {
        return this.number;
    }
    
    public void setNumber(Integer number) {
        this.number = number;
    }
    private Integer numberOfElements;

    public Integer getNumberOfElements() {
        return this.numberOfElements;
    }
    
    public void setNumberOfElements(Integer numberOfElements) {
        this.numberOfElements = numberOfElements;
    }
    private Integer size;

    public Integer getSize() {
        return this.size;
    }
    
    public void setSize(Integer size) {
        this.size = size;
    }
    private Long totalElements;

    public Long getTotalElements() {
        return this.totalElements;
    }
    
    public void setTotalElements(Long totalElements) {
        this.totalElements = totalElements;
    }
    private Integer totalPages;

    public Integer getTotalPages() {
        return this.totalPages;
    }
    
    public void setTotalPages(Integer totalPages) {
        this.totalPages = totalPages;
    }
}
