package io.swagger.api.client.account;

import io.swagger.api.client.account.model.*;

import org.springframework.web.bind.annotation.*;

/**
 * Petstore Sample Application on Spring Cloud 
 * 
 * Auto-generated by api-client-codegen.
 */
public interface AccountClient {

    static final String NAME = "account";


    @RequestMapping(value="/api/account/users", method=RequestMethod.GET)
    Page<User> getUsers(@RequestParam(value="page", defaultValue="0", required=false) Integer page);

  
    @RequestMapping(value="/api/account/users", method=RequestMethod.POST)
    User createUser(@RequestBody(required=true) UserBean bean);

  
    @RequestMapping(value="/api/account/users/{id}", method=RequestMethod.GET)
    User getUser(@PathVariable(value="id", required=true) String id);

  }
